/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CadastrarRestauranteRouteImport } from './routes/cadastrar-restaurante'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantesIndexRouteImport } from './routes/restaurantes.index'
import { Route as RestaurantesIdRouteImport } from './routes/restaurantes.$id'

const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRestauranteRoute = CadastrarRestauranteRouteImport.update({
  id: '/cadastrar-restaurante',
  path: '/cadastrar-restaurante',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIndexRoute = RestaurantesIndexRouteImport.update({
  id: '/restaurantes/',
  path: '/restaurantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesIdRoute = RestaurantesIdRouteImport.update({
  id: '/restaurantes/$id',
  path: '/restaurantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/categorias': typeof CategoriasRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/categorias': typeof CategoriasRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes': typeof RestaurantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar-restaurante': typeof CadastrarRestauranteRoute
  '/categorias': typeof CategoriasRoute
  '/restaurantes/$id': typeof RestaurantesIdRoute
  '/restaurantes/': typeof RestaurantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar-restaurante'
    | '/categorias'
    | '/restaurantes/$id'
    | '/restaurantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar-restaurante'
    | '/categorias'
    | '/restaurantes/$id'
    | '/restaurantes'
  id:
    | '__root__'
    | '/'
    | '/cadastrar-restaurante'
    | '/categorias'
    | '/restaurantes/$id'
    | '/restaurantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarRestauranteRoute: typeof CadastrarRestauranteRoute
  CategoriasRoute: typeof CategoriasRoute
  RestaurantesIdRoute: typeof RestaurantesIdRoute
  RestaurantesIndexRoute: typeof RestaurantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-restaurante': {
      id: '/cadastrar-restaurante'
      path: '/cadastrar-restaurante'
      fullPath: '/cadastrar-restaurante'
      preLoaderRoute: typeof CadastrarRestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/': {
      id: '/restaurantes/'
      path: '/restaurantes'
      fullPath: '/restaurantes/'
      preLoaderRoute: typeof RestaurantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes/$id': {
      id: '/restaurantes/$id'
      path: '/restaurantes/$id'
      fullPath: '/restaurantes/$id'
      preLoaderRoute: typeof RestaurantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarRestauranteRoute: CadastrarRestauranteRoute,
  CategoriasRoute: CategoriasRoute,
  RestaurantesIdRoute: RestaurantesIdRoute,
  RestaurantesIndexRoute: RestaurantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
